# use the setting below to set multiple docs directories.
blogDir = "blog" # can be posts, blog e.t.c . Blogs have special templates
docSections = ["docs", "tutorials"] 
repo = "https://github.com/ecofunctor/ecofunctorSite" 
uniqueHomePage = true # change to false to add sidebar to homepage

# Site logo at navbar
[logo]
darkMode = "images/logo.png"
lightMode = "images/logo.png"

[source] # source code link at navbar
iconDark = "/images/GitHubMarkDark.svg"
iconLight = "/images/GitHubMarkLight.svg"
name = "GitHub"
url = "https://github.com/ecofunctor/ecofunctorSite"

defaultLightingMode = "auto" # other possible values: "dark", "light"
enableDarkMode = false # set to false to disable darkmode by default # user will still have the option to use dark mode
time_format_default = "2006, January 2" 

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 15

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

otherSearchableFields = [
  "Tags",
  "Categories",
  "CustomField",
] # As they appear in frontmatter

# Defaults to true if not set
# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = false

# search
[search]
global = false # turn to `true` to enable global search
on = false
